# -*- coding: utf-8 -*-
"""Untitled155.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1er9qd6gFgQqkAuxSfKGTJOwj3ff7BAQe
"""

import torch

# If there's a GPU avaiable, tell PyTorch to use the GPU,
# otherwise, using the CPU instead.
if torch.cuda.is_available():
  device = torch.device("cuda")
  print('Found GPU:', torch.cuda.get_device_name(0))
else:
  device = torch.device("cpu")
  print('CPU will be used because no GPU available.')