# -*- coding: utf-8 -*-
"""Untitled155.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1er9qd6gFgQqkAuxSfKGTJOwj3ff7BAQe
"""

import torch

def main():
    if torch.cuda.is_available():
        print("Great! PyTorch can access your GPU.")
    else:
        print("Oops! PyTorch cannot access your GPU.")

if __name__ == "__main__":
    main()
